name: ENXHome
main: me.bremado.enx.App
version: 1.0
author: Bremado
commands:
  home:
    description: Teleport to your home
    usage: /home
  sethome:
    description: Set your home
    usage: /sethome
  delhome:
    description: Delete your home
    usage: /delhome